arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: all

plugins: [prettier-plugin-solidity]

overrides:
  - files: ["*.sol"]
    options:
      compiler: 0.5.17
  - files: [contracts/interfaces/*.sol]
    options:
      compiler: 0.8.18
  - files:
      - contracts/interfaces/IBrokerAdmin.sol
      - contracts/interfaces/ICeloToken.sol
      - contracts/interfaces/IExchange.sol
    options:
      compiler: 0.5.17
  - files: [contracts/tokens/patched/*.sol]
    options:
      compiler: 0.8.18
  - files: [contracts/tokens/StableTokenV2.sol]
    options:
      compiler: 0.8.18
  - files: [contracts/governance/**/*.sol]
    options:
      compiler: 0.8.18
  - files: [test/**/*.sol]
    options:
      compiler: ""
  - files: [contracts/oracles/Chainlink*.sol]
    options:
      compiler: 0.8.18
