arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: all

plugins: [prettier-plugin-solidity]

overrides:
  # General Config
  - files: ["*.sol"]
    options:
      compiler: 0.5.17
  - files: [test/**/*.sol]
    options:
      compiler: ""

  # File-specific Config
  - files:
      [
        contracts/common/IERC20MintableBurnable.sol,
        contracts/common/SafeERC20MintableBurnable.sol,
        contracts/goodDollar/**/*.sol,
        contracts/governance/**/*.sol,
        contracts/interfaces/*.sol,
        contracts/libraries/TradingLimits.sol,
        contracts/oracles/Chainlink*.sol,
        contracts/swap/Broker.sol,
        contracts/tokens/patched/*.sol,
        contracts/tokens/StableTokenV2.sol,
      ]
    options:
      compiler: 0.8.18
  - files:
      - contracts/interfaces/IBrokerAdmin.sol
      - contracts/interfaces/ICeloToken.sol
      - contracts/interfaces/IExchange.sol
    options:
      compiler: 0.5.17
