/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPricingModule,
  IPricingModuleInterface,
} from "../IPricingModule";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "tokenInBucketSize",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tokenOutBucketSize",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "spread",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    name: "getAmountIn",
    outputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "tokenInBucketSize",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tokenOutBucketSize",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "spread",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
    ],
    name: "getAmountOut",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "pricingModuleName",
        type: "string",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class IPricingModule__factory {
  static readonly abi = _abi;
  static createInterface(): IPricingModuleInterface {
    return new utils.Interface(_abi) as IPricingModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPricingModule {
    return new Contract(address, _abi, signerOrProvider) as IPricingModule;
  }
}
