name: "Storage Layout"

env:
  FOUNDRY_PROFILE: "ci"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  check_storage_layout:
    name: Check storage layout
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        contract:
          - contracts/swap/Broker.sol:Broker
          - contracts/swap/BiPoolManager.sol:BiPoolManager
          - contracts/swap/Reserve.sol:Reserve
          - contracts/tokens/StableTokenV2.sol:StableTokenV2
          - contracts/governance/Locking.sol:Locking
          - contracts/governance/Emission.sol:Emission
          - contracts/governance/MentoGovernor.sol:MentoGovernor
          - contracts/governance/TimelockController.sol:TimelockController
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: "nightly"
      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "20"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable"
      - name: Check storage layout
        uses: Rubilmax/foundry-storage-check@v3.7
        with:
          contract: ${{ matrix.contract }}
          rpcUrl: ${{ secrets.CELO_MAINNET_RPC_URL }}
          address: "0x1B78f6acD05e7BcB00f74863bfd8a7C264143e37"
          failOnRemoval: true
